name: Docker Publish (Production Images)

on:
  # When changes are pushed to the "main" branch, run it
  push:
    branches:
      - main

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 0'

jobs:
  push:
    runs-on: ubuntu-20.04

    # Configure our deployment strategy. Order is important here and we want it to go: CLI < FPM < FPM-NGINX
    strategy:
      # We want to limit the number of jobs to the number of versions that we're offering (since we want the dependency order to be built correctly)
      max-parallel: 2
      # Set our base image and versions here
      matrix:
        linux-flavor:
          - ubuntu
        version: 
          - "20.04"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/riscv64
            linux/s390x
          pull: true
          push: true
          tags: serversideup/docker-baseimage-s6-overlay-ubuntu:${{ matrix.version }}
  
  update_container_readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/docker-baseimage-s6-overlay-ubuntu
          provider: dockerhub
          short_description: 'Base image for projects that need S6 Overlay'
          readme_file: 'README.md'