name: Docker Publish (Edge - Pull Request)

on:
  pull_request:

env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  push:
    runs-on: ubuntu-20.04
    strategy:
      # We want to limit the number of jobs to the number of versions that we're offering (since we want the dependency order to be built correctly)
      max-parallel: 2
      # Set our base image and versions here
      matrix:
        linux-flavor:
          - ubuntu
        version: 
          - "20.04"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: serversideup/docker-baseimage-s6-overlay-ubuntu:edge-${{ env.PR_NUMBER }}-${{ matrix.version }}