name: Docker Publish (Beta Images)

on:
  # When changes are pushed to the "dev" branch, run it
  push:
    branches:
      - dev

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 7'

jobs:
  push:
    runs-on: ubuntu-20.04

    # Configure our deployment strategy. Order is important here and we want it to go: CLI < FPM < FPM-NGINX
    strategy:
      # We want to limit the number of jobs to the number of versions that we're offering (since we want the dependency order to be built correctly)
      max-parallel: 2
      # Set our base image and versions here
      matrix:
        linux-flavor:
          - ubuntu
        version: 
          - "20.04"

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Build and tag image
        run: docker build --pull php/${{ matrix.linux-flavor }}/${{ matrix.version }}/. --tag serversideup/docker-baseimage-s6-overlay:beta-${{ matrix.linux-flavor }}-${{ matrix.version }}

      - name: Push version image to DockerHub
        run: docker push serversideup/docker-baseimage-s6-overlay:beta-${{ matrix.linux-flavor }}-${{ matrix.version }}