name: Docker Publish (Edge - Pull Request)

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/service_docker-build-and-publish.yml
    with:
      tag-prefix: "edge-${{ github.event.pull_request.number }}-"
      checkout-type: branch
    secrets: inherit